- name: create shipping service
  hosts: shipping
  become: yes
  tasks:
  - name: Install maven
    ansible.builtin.dnf:
      name: maven
      state: present

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"

  - name: delete app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete shipping zip file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: download shipping
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip

  - name: unarchive shipping
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install shipping dependencies
    ansible.builtin.command: mvn clean package 
    args:
      chdir: /app

  - name: copy dependencies
    ansible.builtin.copy:
      src: target/shipping-1.0.jar
      dest: shipping.jar
      remote_src: yes

  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Install mysql client
    ansible.builtin.dnf:
      name: mysql
      state: present

  - name: check schema loaded
    ansible.builtin.command: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 -e 'use cities'
    register: mysql_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_output }}"

  - name: Load schema
    ansible.builtin.shell: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 < /app/db/schema.sql
    when: mysql_output.stdout | int < 0

  - name: Load app user data
    ansible.builtin.shell: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 < /app/db/app-user.sql
    when: mysql_output.stdout | int < 0

  - name: Load master data
    ansible.builtin.shell: mysql -h "{{ MYSQL_HOST }}" -uroot -pRoboShop@1 < /app/db/master-data.sql
    when: mysql_output.stdout | int < 0

  - name: enable and start shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes